# Generated by Django 5.0.6 on 2024-06-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0028_sector_interviewsession_interviewquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre_de_stage',
            name='stage_valide',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='NON', max_length=15),
        ),
    ]
